version: '3'
services:
  vault:
    container_name: vault
    build: .
    restart: always
    env_file: .env
    environment:
      - FLASK_APP=app
      - VAULT_DB_PATH=/data/vault.db
    volumes:
      - vault_data:/data

  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      - CERTBOT_EMAIL=hi@msjr.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - vault

volumes:
  vault_data:
  nginx_secrets:
